server:
  port: 8082

spring:
  application:
    names: api

  jpa:
    hibernate:
      ddl-auto: create-drop              # 실무에서 조심 > db 날라갈 수 있음
    properties:
      hibernate:
        format_sql: true                 # 실무에서 사용하지 않기

        default_batch_fetch_size: 100    # Lazy Loading 시 한 번에 가져올 수
        jdbc:
          batch_size: 100                # 벌크 작업 시 배치 크기
        use_sql_comments: true           # SQL 주석 사용

    open-in-view: false                  # OSIV 끄기

cloud:
  aws:
    s3:
      bucket: muve-bucket
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY_ID}
      secretKey: ${AWS_S3_SECRET_ACCESS_KEY}

logging:
  level:
    org.hibernate.SQL: debug
