server:
  port: 8080

spring:
  application:
    name: admin

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: ${spring.datasource.url}           # AWS Secrets Manager에서 가져옴
    username: ${spring.datasource.username}  # Secrets Manager에서 가져옴
    password: ${spring.datasource.password}  # Secrets Manager에서 가져옴
    driver-class-name: com.mysql.cj.jdbc.Driver

cloud:
  aws:
    s3:
      bucket: muve-bucket
    stack:
      auto: false
    region:
      static: ap-northeast-2
    # credentials 섹션 불필요, Secrets Manager에서 자격 증명을 불러옵니다

secretsmanager:
  name: muve-environment-keys-0  # AWS Secrets Manager에서 자격 증명을 가져오는 경로
  enabled: true

logging:
  level:
    org.hibernate.SQL: warn