server:
  port: 8081

spring:
  application:
    name: admin

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false

  datasource:
    url: ${DB_URL}           # Secrets Manager에서 데이터베이스 URL을 가져옴
    username: ${DB_USERNAME}  # 데이터베이스 사용자명 환경 변수로 설정
    password: ${DB_PASSWORD}  # 데이터베이스 비밀번호 환경 변수로 설정
    driver-class-name: com.mysql.cj.jdbc.Driver

  elasticsearch:
    uris: ${ELASTIC_SEARCH_URL}
    username: ${ELASTIC_SEARCH_USERNAME}
    password: ${ELASTIC_SEARCH_PASSWORD}

cloud:
  aws:
    s3:
      bucket: muve-bucket
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY_ID}
      secret-key: ${AWS_S3_SECRET_ACCESS_KEY}

logging:
  level:
    org.hibernate.SQL: warn