server:
  port: 8081

  jpa:
    hibernate:
      ddl-auto: create-drop # 실무에서 조심 > db 날라갈 수 있음
    properties:
      hibernate:
        format_sql: true # 실무에서 사용하지 않기

cloud:
  aws:
    s3:
      bucket: muve-bucket
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY_ID}
      secretKey: ${AWS_S3_SECRET_ACCESS_KEY}

logging:
  level:
    org.hibernate.SQL: debug


spring:
  h2:
    console:
      enabled: true
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}